#!/usr/bin/env python3
"""Render docs/api/wire-contract.md from engine/proto/ebpfsoc/v1/*.proto.

The .proto files ARE the agent-to-control-plane contract, and their comments are
normative — they record decisions like "no message carries an authoritative
tenant_id, because a payload tenant field could only ever be tamper-detection
telemetry, never an authorization input". That reasoning is what an integrating
team needs, and it already exists in the source.

So this renders rather than restates. No protoc plugin dependency: the doc is
produced from the IDL itself and regenerated by CI, so it cannot drift.

Usage:  ./scripts/ci/gen-protodoc.py [--check]
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PROTO_DIR = ROOT / "engine" / "proto" / "ebpfsoc" / "v1"
OUT = ROOT / "docs" / "api" / "wire-contract.md"


def leading_comments(lines: list[str], idx: int) -> str:
    out: list[str] = []
    j = idx - 1
    while j >= 0 and lines[j].lstrip().startswith("//"):
        out.append(lines[j].lstrip()[2:].strip())
        j -= 1
    out.reverse()
    return "\n".join(out).strip()


def render() -> str:
    L: list[str] = []
    a = L.append
    a("<!-- GENERATED by scripts/ci/gen-protodoc.py — do not edit by hand. -->")
    a("<!-- Regenerate: ./scripts/ci/gen-protodoc.py -->")
    a("")
    a("# Agent ↔ control-plane wire contract (gRPC)")
    a("")
    a("This is the **third** API surface, and the only one that is not HTTP. It is")
    a("specified by protobuf IDL in `engine/proto/ebpfsoc/v1/`; the generated Go")
    a("stubs in `engine/gen/` are committed so consumers build without protoc.")
    a("")
    a("Transport is gRPC over **mutual TLS**. The tenant identity of every call is")
    a("taken from the verified client certificate (`O=<tenant>`), never from the")
    a("message body — see the tenancy note in `common.proto`. An agent therefore")
    a("cannot assign itself a tenant, and a compromised payload cannot widen scope.")
    a("")
    a("`make proto-lint` validates this IDL on every CI run.")
    a("")

    for f in sorted(PROTO_DIR.glob("*.proto")):
        text = f.read_text()
        lines = text.split("\n")
        a(f"## `{f.name}`")
        a("")

        # File-level comment block: the run of // lines before the first
        # syntax/package/option/import declaration.
        header: list[str] = []
        for ln in lines:
            s = ln.strip()
            if s.startswith("//"):
                header.append(s[2:].strip())
            elif s and not s.startswith("//"):
                break
        if header:
            a("> " + "\n> ".join(x if x else "" for x in header))
            a("")

        for i, ln in enumerate(lines):
            m = re.match(r"^service\s+(\w+)", ln.strip())
            if m:
                a(f"### service `{m.group(1)}`")
                doc = leading_comments(lines, i)
                if doc:
                    a("")
                    a(doc)
                a("")
                continue

            m = re.match(r"^\s*rpc\s+(\w+)\s*\(([^)]*)\)\s*returns\s*\(([^)]*)\)", ln)
            if m:
                name, req, resp = (x.strip() for x in m.groups())
                a(f"- **`{name}`**(`{req}`) → `{resp}`")
                doc = leading_comments(lines, i)
                if doc:
                    for d in doc.split("\n"):
                        a(f"  - {d}" if d else "")
                continue

            m = re.match(r"^(message|enum)\s+(\w+)", ln.strip())
            if m:
                kind, name = m.groups()
                doc = leading_comments(lines, i)
                a(f"### {kind} `{name}`")
                if doc:
                    a("")
                    a(doc)
                a("")
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    if not PROTO_DIR.is_dir():
        print(f"no proto dir at {PROTO_DIR}")
        return 1
    doc = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != doc:
            print("DRIFT: docs/api/wire-contract.md does not match the .proto files.")
            print("Fix with: ./scripts/ci/gen-protodoc.py")
            return 1
        print("wire-contract.md matches the IDL")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(doc)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
