#!/usr/bin/env bash
#
# scripts/devstack.sh — run the OSS data tier locally.
#
# deploy/docker-compose.oss.yml declares its passwords as ${VAR:?…}, so a plain
# `docker compose up` on a fresh clone fails with nothing but a cryptic error.
# This script generates deploy/.env (0600, git-ignored) on first run, brings the
# stack up in the order the ADR requires, waits for health, and creates the NATS
# streams — so a new contributor gets a working substrate from one command.
#
#   ./scripts/devstack.sh up          # postgres + nats (the default substrate)
#   ./scripts/devstack.sh up --full   # + clickhouse, keycloak, seaweedfs
#   ./scripts/devstack.sh status
#   ./scripts/devstack.sh logs [service]
#   ./scripts/devstack.sh env         # print the DSNs to export
#   ./scripts/devstack.sh down        # stop, keep the volumes
#   ./scripts/devstack.sh reset       # stop AND destroy every volume
#
# This is a DEV substrate: single node, no replication, Keycloak in start-dev.
# For a server, use scripts/deploy-platform.sh.

LOG_TAG="devstack"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

COMPOSE_FILE="$REPO_ROOT/deploy/docker-compose.oss.yml"
ENV_FILE="$REPO_ROOT/deploy/.env"
CORE_SERVICES=(postgres nats)
FULL_SERVICES=(postgres nats clickhouse keycloak seaweedfs)

compose() { docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"; }

ensure_env() {
  if [[ -f "$ENV_FILE" ]]; then
    ok "using existing $ENV_FILE"
    return 0
  fi
  log "generating $ENV_FILE with fresh passwords"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/devstack.sh — local development only, never commit.
# Regenerate by deleting this file and re-running \`devstack.sh up\`, but note
# that existing volumes keep the OLD passwords: run \`devstack.sh reset\` too.
POSTGRES_PASSWORD=$(gen_secret 32)
CLICKHOUSE_PASSWORD=$(gen_secret 32)
KEYCLOAK_ADMIN_PASSWORD=$(gen_secret 32)
EOF
  chmod 600 "$ENV_FILE"
  ok "$ENV_FILE created (0600)"
}

# The Go tests read these DSNs; printing them is how a developer wires up a
# shell (`eval "$(./scripts/devstack.sh env)"`).
print_env() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  cat <<EOF
export EBPF_TEST_PG_DSN='postgres://soc:${POSTGRES_PASSWORD}@127.0.0.1:5432/ebpf_soc?sslmode=disable'
export EBPF_TEST_CH_DSN='clickhouse://soc:${CLICKHOUSE_PASSWORD}@127.0.0.1:9000/ebpf_soc'
export CP_PG_DSN='postgres://soc:${POSTGRES_PASSWORD}@127.0.0.1:5432/ebpf_soc?sslmode=disable'
export NATS_URL='nats://127.0.0.1:4222'
EOF
}

cmd_up() {
  need_cmd docker
  docker info >/dev/null 2>&1 || die "the Docker daemon is not running"
  ensure_env

  local services=("${CORE_SERVICES[@]}")
  if [[ "${1:-}" == "--full" ]]; then services=("${FULL_SERVICES[@]}"); fi

  log "starting: ${services[*]}"
  compose up -d "${services[@]}"

  wait_for 120 "postgres" compose exec -T postgres pg_isready -U soc -d ebpf_soc \
    || die "postgres never became ready — ./scripts/devstack.sh logs postgres"
  wait_for 60 "nats" curl -fsS http://127.0.0.1:8222/healthz \
    || die "nats never became ready"

  for s in "${services[@]}"; do
    case "$s" in
      clickhouse) wait_for 120 "clickhouse" curl -fsS http://127.0.0.1:8123/ping || die "clickhouse never became ready" ;;
      keycloak)   wait_for 240 "keycloak"   curl -fsS http://127.0.0.1:8080/realms/master || die "keycloak never became ready" ;;
    esac
  done

  # Streams the uplink publishes to. `nats` CLI is optional, so this degrades to
  # a hint rather than a hard failure.
  if have_cmd nats; then
    log "ensuring JetStream streams"
    nats --server=nats://127.0.0.1:4222 stream add TELEMETRY \
      --subjects 'telemetry.>' --storage file --retention limits --max-age 24h \
      --defaults >/dev/null 2>&1 || dim "stream TELEMETRY already exists"
    ok "JetStream streams ready"
  else
    dim "nats CLI not installed — the control plane creates its own streams on first publish"
  fi

  log "applying migrations"
  "$SCRIPTS_DIR/migrate.sh" up --engine postgres --env-file "$ENV_FILE" \
    || warn "postgres migrations failed — the app self-bootstraps its base tables, but retention/indexes are missing"

  printf '\n'
  ok "stack up"
  dim "postgres    127.0.0.1:5432   db=ebpf_soc user=soc"
  dim "nats        127.0.0.1:4222   (monitor :8222)"
  if [[ "${1:-}" == "--full" ]]; then
    dim "clickhouse  127.0.0.1:9000   (http :8123)"
    dim "keycloak    127.0.0.1:8080   admin / see $ENV_FILE"
    dim "seaweedfs   127.0.0.1:8333   (S3)"
  fi
  printf '\n  Wire up a shell:  %seval "$(./scripts/devstack.sh env)"%s\n\n' "$C_BOLD" "$C_RESET"
}

cmd_down()   { compose down; ok "stack stopped (volumes kept)"; }
cmd_status() { compose ps; }
cmd_logs()   { compose logs -f --tail=100 "${@:-}"; }

cmd_reset() {
  warn "this destroys every volume: all events, control state, and the Keycloak realm"
  confirm "Really wipe the local stack?" n || { log "aborted"; exit 0; }
  compose down -v
  rm -f "$ENV_FILE"
  ok "stack destroyed and $ENV_FILE removed — the next 'up' starts clean"
}

case "${1:-up}" in
  up)     shift; cmd_up "$@" ;;
  down)   cmd_down ;;
  status|ps) cmd_status ;;
  logs)   shift; cmd_logs "$@" ;;
  env)    print_env ;;
  reset)  cmd_reset ;;
  -h|--help) sed -n '3,21p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) die "unknown command: $1 (try: up, down, status, logs, env, reset)" ;;
esac
