apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sensitive-file-access"
spec:
  kprobes:
    - call: "security_file_permission"
      syscall: false
      return: true
      args:
        - index: 0
          type: "file"
        - index: 1
          type: "int"
      returnArg:
        index: 0
        type: "int"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/etc/shadow"
                - "/etc/passwd"
                - "/etc/sudoers"
                - "/root/.ssh/"
                - "/var/lib/ebpf-engine/honey/"
            - index: 1
              operator: "Mask"
              values:
                - "2"   # MAY_WRITE
                - "4"   # MAY_READ
          matchActions:
            - action: Post
